### ISSUE TITLE
Race condition on shutdown

### ISSUE THREAD

**Issue by baldurk** [jonasmr/microprofile#12]
I'm using microprofile in a dll that can be unloaded before the executable closes. I call `MicroProfileShutdown` before the dll is unloaded (not in dllmain or anything, I get a function call to shut everything down).

However for the webserver thread this only sets `S.nMicroProfileShutdown = 1` and returns, it doesn't synchronise on `WebSocketSendThread` actually finishing, so there's a gap between `MicroProfileShutdown` returning and the thread exiting, where my dll can get unloaded and suddenly the thread that's running doesn't have code to execute because the page is gone.

I think it should do something like `MicroProfileThreadJoin(&S.WebSocketSendThread);` after setting the shutdown flag to 1?

**Comment by jonasmr** [comment]
should be fixed as per commit above.
Thank you for the suggestion, you are indeed correct.
