### ISSUE TITLE
memset will clear std::atomic

### ISSUE THREAD

**Issue by madebr** [jonasmr/microprofile#28]
On
https://github.com/jonasmr/microprofile/blob/bca802bae1e252fde133dff54c47ba8d3a950c1d/microprofile.cpp#L1050
and
https://github.com/jonasmr/microprofile/blob/bca802bae1e252fde133dff54c47ba8d3a950c1d/microprofile.cpp#L1222
An object of `MicroProfileThreadLog` is cleared.

This operation is unsafe because the `std::atomic` in there have no trivial copy-assignment.

```
/home/maarten/programming/openrw/external/microprofile/microprofile/microprofile.cpp:1221: warning: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘struct MicroProfileThreadLog’ with no trivial copy-assignment; use value-initialization instead [-Wclass-memaccess]
         memset(pLog, 0, sizeof(*pLog));
                                      ^
```

**Comment by jonasmr** [comment]
Isn't this just the compiler being silly? 
Does a platform actually exist where this is a problem?

**Comment by madebr** [comment]
This warning was observed on older mac builds of our [project](https://github.com/rwengine/openrw/).
But I cannot reproduce this warning anymore.
Let's assume it got fixed :).
Thanks for the answer!
