### ISSUE TITLE
D3D12 GPU scopes are broken

### ISSUE THREAD

**Issue by akaStiX** [jonasmr/microprofile#39]
When I try to profile our game with markers for GPU I get crash on latest microprofile.
I think I managed to trace down this issue.
Problem seems to happen in MicroProfileGpuFlip, when doing ResolveQueryData It's input, nStart points to the first marker added in this frame, but we saturate GPU with a LOT of work, so it just finishes rendering previous frame. So queries from this frame were not yet executed and, thus, timestamps for any queries will be 0.
Eventually when microprofile tries to submit information about markers it takes timestamp (0), does some math on it ends up with negative value and crashes on this assert MP_ASSERT(nTicks < 0x8000000000000000). line 3070.
It works in loading screen, when all we render is just a few sprites, but crashes as soon as we loaded first level.
It looks like this code:
```
		nCount = S.pGPU->nFrameCount.exchange(0);
		nStart = S.pGPU->nFrameStart;
		S.pGPU->nFrameStart = (S.pGPU->nFrameStart + nCount) % MICROPROFILE_D3D_MAX_QUERIES;
		uint32_t nEnd = MicroProfileMin(nStart + nCount, (uint32_t)MICROPROFILE_D3D_MAX_QUERIES);
		MP_ASSERT(nStart != nEnd);
		uint32_t nSize = nEnd - nStart;
		pCommandList->ResolveQueryData(S.pGPU->NodeState[nNode].pHeap, D3D12_QUERY_TYPE_TIMESTAMP, nStart, nEnd - nStart, S.pGPU->pBuffer, nStart * sizeof(int64_t));
```
has to be rewritten to query data for previous markers, not current, but I might be wrong.

**Comment by jonasmr** [comment]
It should not be possible for what you describe to happen.
I think its pretty hard to discuss without having code.
Can you modify the d3d12 sample to do what you describe?

**Comment by akaStiX** [comment]
So I debugged this a little bit more and indeed it was a bug in my integration code. I missed one small thing in complicated multithreaded dispatch code, took me a while to find the issue.
Sorry for misinformation
