### ISSUE TITLE
any interest in direct-to-terminal output?

### ISSUE THREAD

**Issue by dankamongmen** [jonasmr/microprofile#79]
first off, let me say this project looks awesome; very nicely done.

i'm the author of a TUI/character graphics library called [Notcurses](https://notcurses.com). it just so happens that i was planning to *this weekend* start a similarish project from scratch, loosely described here:

  https://github.com/dankamongmen/notcurses/issues/381

this was going to involve running perf atop arbitrary binaries rather than being embedded into them, but your approach already has so much of the control end done that i think i'd rather leverage your work on microprofile. so, i'm going to look into making live terminal output an alternative to your webserver+browser approach. is this something that would interest y'all as upstream authors -- i.e. something i ought plan to PR, something that doesn't clash with your vision -- or ought i just plan to keep it as a fork?

thanks for your time evaluating this (admittedly somewhat vague) idea.

**Comment by jonasmr** [comment]
Hi.

I think in its current state, you'll find that the web interface and the logging side of things are pretty closely tied together(and not documented).

The Live ui uses a websocket. Piggybacking on that would definitely be possible for you.
The full capture view is a full webpage, which will obviously be harder. I'd also say its not something for a console, but looking at your project, it seems like the wrong thing to say to you:).

I have it on my list to make the logging more seperate from the UI which would obviously help, but unfortunately its been on my list for quite some time.

**Comment by dankamongmen** [comment]
thanks for the thoughtful feedback. i'll go ahead and close this bug up so as not to pollute your issue tracker. i'll take a look at how this is being done, but it sounds like the best console solution may well be a terminal-capable browser using your existing webpage. thanks for your time!
