### ISSUE TITLE
OpenGL profiling?

### ISSUE THREAD

**Issue by gaborpapp** [jonasmr/microprofile#8]
Is OpenGL profiling deprecated? I cannot find a demo that does this.

Tried to build microprofile with `-DMICROPROFILE_GPU_TIMERS=1 -DMICROPROFILE_GPU_TIMERS_GL=1` on OS X. After adding the missing gl headers to `microprofile.cpp` the build fails with a linker error that no `_MicroProfileGpuFlip` and `_MicroProfileGpuShutdown` are found.

Any help would be appreciated.

**Comment by Skylark13** [comment]
These implementations made it work for me. Not sure if more would be needed, but it seems sufficient (on Windows).

```C
uint32_t MicroProfileGpuFlip(void* pContext)
{
    uint32_t nFrameTimeStamp = MicroProfileGpuInsertTimeStamp(pContext);
    return nFrameTimeStamp;
}

void MicroProfileGpuShutdown()
{
    glDeleteQueries(MICROPROFILE_GL_MAX_QUERIES, &S.pGPU->GLTimers[0]);
    MP_FREE(S.pGPU);
    S.pGPU = 0;
}
```

You'll also need to add this to MicroProfileGpuInitGL() :

```C
    S.pGPU = MP_ALLOC_OBJECT(MicroProfileGpuTimerState);
```

**Comment by jonasmr** [comment]
Hi.
Some osx versions ago, apple decided to ditch support for the timestamp functionality, which is needed by the microprofiler.

I never got around to making a demo for windows, and thus testing it.

**Comment by Skylark13** [comment]
Well there's a PR all ready to merge above :-)

**Comment by jonasmr** [comment]
I was just trying to merge the pull request as suggested by some other user, but now it disappeared.
I have no clue where its gone.
I will look into this.

**Comment by jonasmr** [comment]
found the user. his profile seems to be gone. https://github.com/Skylark13
I will reimplement it

**Comment by jonasmr** [comment]
with the commit mentioned above, and the one from 1 minute ago, there is now an opengl sample program.

It still wont work on OSX unfortunately, and there is no way of fixing it.

**Comment by Skylark13** [comment]
In my case, it was to use with OpenGL on Windows, so that's fine. Thanks!
